#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_BACKGROUND 30
#define ID_TEX_ENEMY2 40


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_PARAGOOMBA 6
#define OBJECT_TYPE_GROUND 7
#define OBJECT_TYPE_QUESTIONBLOCK 8
#define OBJECT_TYPE_VENUS 9
#define OBJECT_TYPE_POWERUPITEM 10
#define OBJECT_TYPE_PIPE 11
#define OBJECT_TYPE_COINITEM 12
#define OBJECT_TYPE_COLORBLOCK 13
#define OBJECT_TYPE_BIGBUSH 14
#define OBJECT_TYPE_DECORATION 15
#define OBJECT_TYPE_KOOPA 16
#define OBJECT_TYPE_WOODBLOCK 17
#define OBJECT_TYPE_PIRANHA 18

#define OBJECT_TYPE_PORTAL	50
#define OBJECT_TYPE_PIT	51
#define OBJECT_TYPE_SPAWNBOX 52
#define OBJECT_TYPE_HUD 53
#define OBJECT_TYPE_EXTRALIFEMUSHROOM 54

#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK_IDLE 20000
#define ID_SPRITE_BRICK_BOTTOM 20001
#define ID_SPRITE_BRICK_CENTER 20002
#define ID_SPRITE_BRICK_TOP 20003
#define ID_SPRITE_BRICK_USED 20004

#define ID_SPRITE_WOODBLOCK 20010

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_PARAGOOMBA 35000
#define ID_SPRITE_PARAGOOMBA_WALK_WING_RIGHT_FOOT_UP (ID_SPRITE_PARAGOOMBA + 1)
#define ID_SPRITE_PARAGOOMBA_WALK_WING_LEFT_FOOT_UP (ID_SPRITE_PARAGOOMBA + 2)
#define ID_SPRITE_PARAGOOMBA_FLY_RIGHT_FOOT_UP (ID_SPRITE_PARAGOOMBA + 3)
#define ID_SPRITE_PARAGOOMBA_FLY_LEFT_FOOT_UP (ID_SPRITE_PARAGOOMBA + 4)
#define ID_SPRITE_PARAGOOMBA_WALK_RIGHT_FOOT_UP (ID_SPRITE_PARAGOOMBA + 5)
#define ID_SPRITE_PARAGOOMBA_WALK_LEFT_FOOT_UP (ID_SPRITE_PARAGOOMBA + 6)
#define ID_SPRITE_PARAGOOMBA_DIE (ID_SPRITE_PARAGOOMBA + 7)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)
#define ID_SPRITE_LAKITU_CLOUD (ID_SPRITE_CLOUD+4000)

#define ID_SPRITE_GROUND 60000
#define ID_SPRITE_GROUND_BEGIN (ID_SPRITE_GROUND + 1000)
#define ID_SPRITE_GROUND_MIDDLE (ID_SPRITE_GROUND + 2000)
#define ID_SPRITE_GROUND_END (ID_SPRITE_GROUND + 3000)
#define ID_SPRITE_UNDER_GROUND_BEGIN (ID_SPRITE_GROUND + 4000)
#define ID_SPRITE_UNDER_GROUND_MIDDLE (ID_SPRITE_GROUND + 5000)

#define ID_SPRITE_QUESTIONBLOCK_CENTER 70000
#define ID_SPRITE_QUESTIONBLOCK_RIGHT (ID_SPRITE_QUESTIONBLOCK_CENTER + 1000)
#define ID_SPRITE_QUESTIONBLOCK_MISSING (ID_SPRITE_QUESTIONBLOCK_CENTER + 2000)
#define ID_SPRITE_QUESTIONBLOCK_LEFT (ID_SPRITE_QUESTIONBLOCK_CENTER + 3000)
#define ID_SPRITE_QUESTIONBLOCK_USED (ID_SPRITE_QUESTIONBLOCK_CENTER + 4000)

#define ID_SPRITE_SUPERMUSHROOM 80000
#define ID_SPRITE_SUPERLEAF_LEFT 81000
#define ID_SPRITE_SUPERLEAF_RIGHT 82000
#define ID_SPRITE_EXTRALIFEMUSHROOM 83000

#define ID_SPRITE_COINITEM_FULL 90000
#define ID_SPRITE_SUPERLEAF_HALF 91000
#define ID_SPRITE_SUPERLEAF_EDGE 92000

#define ID_SPRITE_KOOPA 103000
#define ID_SPRITE_KOOPA_WALKING_LEFT_OPENMOUTH (ID_SPRITE_KOOPA + 1)
#define ID_SPRITE_KOOPA_WALKING_LEFT_CLOSEDMOUTH (ID_SPRITE_KOOPA + 2)
#define ID_SPRITE_KOOPA_WALKING_RIGHT_OPENMOUTH (ID_SPRITE_KOOPA + 3)
#define ID_SPRITE_KOOPA_WALKING_RIGHT_CLOSEDMOUTH (ID_SPRITE_KOOPA + 4)

#define ID_SPRITE_KOOPA_SHELL_UPRIGHT_IDLE (ID_SPRITE_KOOPA + 5)
#define ID_SPRITE_KOOPA_SHELL_UPRIGHT_MOVING_CENTER (ID_SPRITE_KOOPA + 6)
#define ID_SPRITE_KOOPA_SHELL_UPRIGHT_MOVING_LEFT (ID_SPRITE_KOOPA + 7)
#define ID_SPRITE_KOOPA_SHELL_UPRIGHT_MOVING_RIGHT (ID_SPRITE_KOOPA + 8)
#define ID_SPRITE_KOOPA_SHELL_UPRIGHT_REVIVE (ID_SPRITE_KOOPA + 9)

#define ID_SPRITE_KOOPA_SHELL_FLIPPED_IDLE (ID_SPRITE_KOOPA + 10)
#define ID_SPRITE_KOOPA_SHELL_FLIPPED_MOVING_CENTER (ID_SPRITE_KOOPA + 11)
#define ID_SPRITE_KOOPA_SHELL_FLIPPED_MOVING_LEFT (ID_SPRITE_KOOPA + 12)
#define ID_SPRITE_KOOPA_SHELL_FLIPPED_MOVING_RIGHT (ID_SPRITE_KOOPA + 13)
#define ID_SPRITE_KOOPA_SHELL_FLIPPED_REVIVE (ID_SPRITE_KOOPA + 14)

#define ID_SPRITE_GREEN_KOOPA_WALKING_LEFT_OPENMOUTH (ID_SPRITE_KOOPA + 15)
#define ID_SPRITE_GREEN_KOOPA_WALKING_LEFT_CLOSEDMOUTH (ID_SPRITE_KOOPA + 16)
#define ID_SPRITE_GREEN_KOOPA_WALKING_RIGHT_OPENMOUTH (ID_SPRITE_KOOPA + 17)
#define ID_SPRITE_GREEN_KOOPA_WALKING_RIGHT_CLOSEDMOUTH (ID_SPRITE_KOOPA + 18)

#define ID_SPRITE_GREEN_KOOPA_SHELL_UPRIGHT_IDLE (ID_SPRITE_KOOPA + 19)
#define ID_SPRITE_GREEN_KOOPA_SHELL_UPRIGHT_MOVING_CENTER (ID_SPRITE_KOOPA + 20)
#define ID_SPRITE_GREEN_KOOPA_SHELL_UPRIGHT_MOVING_LEFT (ID_SPRITE_KOOPA + 21)
#define ID_SPRITE_GREEN_KOOPA_SHELL_UPRIGHT_MOVING_RIGHT (ID_SPRITE_KOOPA + 22)
#define ID_SPRITE_GREEN_KOOPA_SHELL_UPRIGHT_REVIVE (ID_SPRITE_KOOPA + 23)

#define ID_SPRITE_GREEN_KOOPA_SHELL_FLIPPED_IDLE (ID_SPRITE_KOOPA + 24)
#define ID_SPRITE_GREEN_KOOPA_SHELL_FLIPPED_MOVING_CENTER (ID_SPRITE_KOOPA + 25)
#define ID_SPRITE_GREEN_KOOPA_SHELL_FLIPPED_MOVING_LEFT (ID_SPRITE_KOOPA + 26)
#define ID_SPRITE_GREEN_KOOPA_SHELL_FLIPPED_MOVING_RIGHT (ID_SPRITE_KOOPA + 27)
#define ID_SPRITE_GREEN_KOOPA_SHELL_FLIPPED_REVIVE (ID_SPRITE_KOOPA + 28)

#define ID_SPRITE_VENUS 110000

#define ID_SPRITE_HUD 120000

#define ID_SPRITE_SHADOW_TOP 100040
#define ID_SPRITE_SHADOW_RIGHT 100041

#define ID_SPRITE_BROKEN_BRICK_PIECE 130000

